#!/bin/bash

# first setup ssh

sudo pacman -S zsh git tmux neovim wezterm fzf rg fd delta stow jq
chsh -s $(which zsh)

git clone git@github.com:kleinepls/dotdotdot.git ~/dotfiles
cd dotfiles
stow wezterm
stow zsh
stow tmux
ln -s ~/dotfiles/nvim ~/.config/nvim
mkdir -p ~/.scripts
ln ~/dotfiles/tmux-sessionizer ~/.scripts
cd ~

git clone git@github.com:zsh-users/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting
git clone git@github.com:zsh-users/zsh-history-substring-search.git ~/.zsh/zsh-history-substring-search
git clone git@github.com:zsh-users/zsh-autosuggestions.git ~/.zsh/zsh-autosuggestions
git clone git@github.com:Aloxaf/fzf-tab.git ~/.zsh/fzf-tab

curl -sS https://starship.rs/install.sh | sh
starship preset nerd-font-symbols -o ~/.config/starship.toml
curl https://mise.run | sh
mise use node
mise use go

