#!/bin/bash

# first setup ssh

sudo pacman -S --noconfirm --needed zsh git tmux wezterm fzf ripgrep fd git-delta stow jq
chsh -s $(which zsh)

mkdir ~/code
mv ~/.zshrc ~/.zshrc.old
ln -s ~/dotfiles/nvim ~/.config/nvim
cd dotfiles
stow zsh
stow wezterm
stow tmux
mkdir -p ~/.scripts
ln ~/dotfiles/tmux-sessionizer ~/.scripts
cd ~

git clone git@github.com:tmux-plugins/tpm.git ~/.tmux/plugins/tpm
git clone git@github.com:zsh-users/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting
git clone git@github.com:zsh-users/zsh-history-substring-search.git ~/.zsh/zsh-history-substring-search
git clone git@github.com:zsh-users/zsh-autosuggestions.git ~/.zsh/zsh-autosuggestions
git clone git@github.com:Aloxaf/fzf-tab.git ~/.zsh/fzf-tab

curl -sS https://starship.rs/install.sh | sh
starship preset nerd-font-symbols -o ~/.config/starship.toml
curl https://mise.run | sh
curl https://sh.rustup.rs -sSf | sh

