#!/bin/bash

# first setup ssh
systemctl --user enable ssh-agent.service
echo "AddKeysToAgent yes" >> ~/.ssh/config

git config --global --add url."git@github.com:".insteadOf "https://github.com/"

sudo pacman -Syu
sudo pacman -S --noconfirm --needed zsh tmux wezterm fzf ripgrep fd git-delta stow jq bat
chsh -s $(which zsh)

sudo pacman -S --noconfirm otf-commit-mono-nerd

mv ~/.zshrc ~/.zshrc.old
mkdir ~/code ~/.scripts
ln -s ~/dotfiles/nvim ~/.config/nvim
ln ~/dotfiles/tmux-sessionizer ~/.scripts
cd ~/dotfiles
stow zsh
stow wezterm
stow tmux
cd ~

git clone git@github.com:tmux-plugins/tpm.git ~/.tmux/plugins/tpm
git clone git@github.com:zsh-users/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting
git clone git@github.com:zsh-users/zsh-autosuggestions.git ~/.zsh/zsh-autosuggestions
git clone git@github.com:Aloxaf/fzf-tab.git ~/.zsh/fzf-tab

curl -sS https://starship.rs/install.sh | sh
starship preset nerd-font-symbols -o ~/.config/starship.toml
curl https://mise.run | sh
curl https://sh.rustup.rs -sSf | sh
mise use go
mise use node

sudo pacman -S --noconfirm docker docker-compose
sudo systemctl enable docker.socket
sudo systemctl start docker.socket
sudo usermod -aG docker $USER
newgrp docker

sudo pacman -S --needed --noconfirm base-devel cmake ninja curl
git clone git@github.com:neovim/neovim.git ~/sources/neovim
cd ~/sources/neovim
sudo make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
cd ~
nvim --version

