#!/bin/bash

session=$(find ~ ~/.config ~/.scripts ~/sources ~/code -mindepth 1 -maxdepth 1 -type d | fzf)
session_name=$(basename "$session" | tr . _)

if [ ! $session_name ]; then
    exit 1
fi

if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux new-session -s "$session_name" -c "$session" -d
fi 

if [ ! $TMUX ]; then
    tmux attach -t "$session_name"
else
    tmux switch-client -t "$session_name"
fi
